language: node_js
services:
  - docker
node_js:
  - "10"
  - "node"
cache: npm
before_install:
 - docker pull gabcas28/image-repository
install:
 - docker run gabcas28/image-repository -v `pwd`:/app
script: npm test