name: CI with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List directory
        run: pwd
      - name: List files
        run: ls
      - name: Get and run docker image
        run: sudo docker run --rm -tv `pwd`:/app gabcas28/image-repository
