name: CI with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: gabcas28/image-repository:latest
      options: -v ~/:/app
    steps:
      - uses: actions/checkout@v2
      - name:  What OS is running
        run: uname -a
      - name: What node version do we have
        run: npm ci
      - name: Run tests
        run: npm test

