name: CI with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: find actual directory
        id: dir
        run: pwd
      - uses: addnab/docker-run-action@v1
        with:
          image: gabcas28/image-repository:latest
          options: -tv /__w/Image-Repository/Image-Repository:/app gabcas28/image-repository
          run: npm test
