name: CI with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get and run docker image
        run: docker run -v `pwd`:/app gabcas28/image-repository
        continue-on-error: true
