name: CI with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get and run docker image
        run: sudo docker run --rm -tv `pwd`:/app gabcas28/image-repository
