name: CI with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : directory
        run: pwd

    container: 
      image: gabcas28/image-repository:latest
      options: -tv /home/runner/work/Image-Repository/Image-Repository:/app gabcas28/image-repository
