name: CI with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: gabcas28/image-repository:latest
      options: -tv /__w/Image-Repository/Image-Repository:/app
    steps:
      - name: Run tests
        run: npm test
